import { A2AClient } from 'a2a-sdk-google';
import { z } from 'zod';
import type { McpTool } from '../interfaces/tool.interface';

const partSchema = z.object({
  kind: z.literal('text'),
  text: z.string().describe('The text of the message part'),
});

const messageSchema = z.object({
  contextId: z.string().describe('The context ID of the message, is autogenerated by the client'),
  messageId: z
    .string()
    .describe('The message ID is Autogenerated by the agent AI the first message must be ""'),
  parts: partSchema.array().describe('The parts of the message'),
});

const parameters = {
  agentUrl: z.string().describe('The URL of the agent to send the message to'),
  body: z.object({
    params: z.object({
      message: messageSchema,
    }),
  }),
} as const;

type Parameters = z.infer<z.ZodObject<typeof parameters>>;

class SendMessageToAgentTool implements McpTool<typeof parameters> {
  name = 'send-message-to-agent';
  description = 'Sends a message to an agent, the agent will respond with a message.';
  parameters = parameters;
  handler = async (context: Parameters) => {
    try {
      const client = new A2AClient({
        baseUrl: context.agentUrl,
      });

      const sendMessage = await client.sendMessage(context.body.params.message);

      return {
        content: [
          {
            type: 'text' as const,
            text: JSON.stringify(sendMessage, null, 2),
          },
        ],
      };
    } catch (error) {
      return {
        content: [
          {
            type: 'text' as const,
            text: `Error retrieving user details: ${
              error instanceof Error ? error.message : 'Unknown error'
            }`,
          },
        ],
      };
    }
  };
}

export const sendMessageToAgent = new SendMessageToAgentTool();
